### ISSUE TITLE
Fails on Ruby 2.0.0

### ISSUE THREAD

**Issue by RohitRox** [xogroup/rosie-aws#5]
``` bash
$ rosie
/usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- io/console (LoadError)
	from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/ec2-user/.gem/ruby/2.0/gems/thor-0.19.4/lib/thor/shell/basic.rb:2:in `<top (required)>'
	from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/ec2-user/.gem/ruby/2.0/gems/thor-0.19.4/lib/thor/shell/color.rb:1:in `<top (required)>'
	from /home/ec2-user/.gem/ruby/2.0/gems/thor-0.19.4/lib/thor/shell.rb:17:in `shell'
	from /home/ec2-user/.gem/ruby/2.0/gems/thor-0.19.4/lib/thor/base.rb:443:in `start'
	from /home/ec2-user/.gem/ruby/2.0/gems/rosie-aws-0.1.1/bin/rosie:3:in `<top (required)>'
	from /home/ec2-user/bin/rosie:23:in `load'
	from /home/ec2-user/bin/rosie:23:in `<main>'
$ ruby -v
ruby 2.0.0p648 (2015-12-16) [x86_64-linux]

```

**Comment by nrodriguez** [comment]
I'm wondering now if the better solution isn't just to upgrade the ruby version.

**Comment by RohitRox** [comment]
Agree
